Домашняя работа Разметка
htmlacademy-htmlcss/1027921-sedona-34 pull request #2
Opened 2022-05-26 13:14 UTC by Volkovak27

2022-05-27 06:49 UTC, Kartaviy-arteom requested changes

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +<header class="page-header">
Соблюдай, пожалуйста, вложенность в документе. Это потом сильно упростит с ним работы. Для быстрого форматирования в VSCode есть горячие клавиши: Windows — Shift + Alt + F и macOS — ⇧⌥F

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +  <h2 class="visually-hidden">Преимущества</h2>
я бы подумал над тем чтобы причины и <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p> находились в одной секции.

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +    <p class="advantages-description-sedona">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
для того чтобы стилизовать это как на макете, тебе нужно будет сгруппировать эти 3 элемента, можно использовать для этого div. Аналогично и в других элементах списка

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +  <ul class="advantages-list">
Если в списке важна последовательность элементов, можно использовать ol.

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +        <input type="text" id="appointment-email" name="appointment-date" placeholder="Ваш e-mail">
нужно добавить label https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-05

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +  <p class="footer-call">+7 (812) 812-12-12</p>
это будет ссылка, вида <a href="tel:+1234567890">. Здесь параграф ради параграфа

2022-05-27 06:49 UTC, Kartaviy-arteom commented on index.html
> +  <img class="logo-footer" src="" alt="Логотип сайта Седона.">
Здесь должна быть ссылка на HTMLAcademy

2022-05-27 07:43 UTC, Volkovak27 commented on index.html
> +<header class="page-header">
исправила

2022-05-27 07:45 UTC, Volkovak27 commented on index.html
> +  <h2 class="visually-hidden">Преимущества</h2>
`   <section class="advantages">
        <h2>Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
        <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
        <ul class="advantages-list">
          <li class="advantages-item">`

2022-05-27 07:46 UTC, Volkovak27 commented on index.html
> +  <h2 class="visually-hidden">Преимущества</h2>
Удалила заголовок, который нужно было прописывать класс для скрытия и внесла в секцию с преимуществами.

2022-05-27 10:46 UTC, Volkovak27 commented on index.html
> +    <p class="advantages-description-sedona">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
исправила.

2022-05-27 10:47 UTC, Volkovak27 commented on index.html
> +  <ul class="advantages-list">
исправила

2022-05-27 11:06 UTC, Volkovak27 commented on index.html
> +        <input type="text" id="appointment-email" name="appointment-date" placeholder="Ваш e-mail">
добавила

2022-05-27 12:15 UTC, Volkovak27 commented on index.html
> +  <p class="footer-call">+7 (812) 812-12-12</p>
готово

2022-05-27 12:15 UTC, Volkovak27 commented on index.html
> +  <img class="logo-footer" src="" alt="Логотип сайта Седона.">
готово

2022-05-30 16:51 UTC, Kartaviy-arteom approved these changes

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +                        <input class="control-input" type="checkbox" name="swimm-pool" checked>
https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-02 несколько спорное сокращение в наименовании атрибута

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +                        <input class="control-input" type="checkbox" name="swimm-pool">
неверное ты хотела использовать другое значение для name

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +                        <input class="control-input" type="radio" name="hotels" value="hotels"checked>
атрибуты должны быть разделены пробелом  value="hotels"checked

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +              <button class="button-catalog" type="submit">Сбросить</button>
type reset

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +          </a>
вполне может быть списком например "видов отображения"

2022-05-30 16:51 UTC, Kartaviy-arteom commented on catalog.html
> +              <p class="product-card-category">Гостиница</p>
для одного слова `<p`> выглядит избыточно

2022-05-30 16:51 UTC, Kartaviy-arteom commented on index.html
> +          </li>
трудно понять, что куда вложено, нужно уделить дополнительное время форматированию разметки.
Удели, пожалуйста, время этой статье про alt для изображения https://up.htmlacademy.ru/htmlcss/34/book/2.7

2022-05-30 16:51 UTC, Kartaviy-arteom commented on index.html
> +          </li>
Вот эти 3 li: жилье, сувениры, еда можно сделать списком внутри первой li. У тебя выше указано рассмотрим 5 причин, а потом список в котором уже гораздо больше элементов, выглядит неоднозначно. Картинки декоративные, в разметке они здесь не нужны, добавим на css. https://up.htmlacademy.ru/htmlcss/34/book/2.8

2022-05-30 16:51 UTC, Kartaviy-arteom commented on index.html
> +        <a class="button button-all" href="#">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
тебе не обязательно писать весь текст прописными, чтобы отобразить его на странице. Можно использовать это https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

2022-05-30 16:51 UTC, merged

2022-05-31 17:07 UTC, Volkovak27 commented on catalog.html
> +                        <input class="control-input" type="checkbox" name="swimm-pool" checked>
написала просто pool

2022-05-31 17:08 UTC, Volkovak27 commented on catalog.html
> +                        <input class="control-input" type="checkbox" name="swimm-pool">
да, скопировала и не сменила name. исправила.

2022-05-31 17:09 UTC, Volkovak27 commented on catalog.html
> +                        <input class="control-input" type="radio" name="hotels" value="hotels"checked>
надо поработать над проверкой кода. Знаю, что тут должен быть пробел.

2022-05-31 17:12 UTC, Volkovak27 commented on index.html
> +        <a class="button button-all" href="#">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
Да, видимо так скопировала с фигмы. Исправила.

2022-05-31 17:14 UTC, Volkovak27 commented on catalog.html
> +              <p class="product-card-category">Гостиница</p>
исправила на span

2022-05-31 17:15 UTC, Volkovak27 commented on catalog.html
> +              <button class="button-catalog" type="submit">Сбросить</button>
а, ну точно. Кнопка сброса. Ступила) Исправила.

2022-06-03 12:24 UTC, Volkovak27 commented on index.html
> +          </li>
отредактировала наименование классов. Заодно чуть поточнее написала alt для картинки.

2022-06-03 12:24 UTC, Volkovak27 commented on index.html
> +          </li>
сделала