Домашнее задание Графика
htmlacademy-htmlcss/1027921-sedona-34 pull request #3
Opened 2022-06-03 14:53 UTC by Volkovak27

Добавила изображение. Исправила предыдущие замечания в разметке. Добавила рейтингу звездочки.

2022-06-04 12:03 UTC, Kartaviy-arteom requested changes
Вообщем, что нужно исправить: иконки в формате svg, наименование в соответствии с критериями, убрать декоративную графику из разметки, удалить неиспользуемые файлы

2022-06-04 12:03 UTC, Kartaviy-arteom commented on catalog.html
> +        </ul>
наверное ты хотела указать разное содержимое для span-ов

2022-06-04 12:03 UTC, Kartaviy-arteom commented on catalog.html
> +          <img class="page-header-logo" src="/images/HTML Academy.svg" width="115" height="33" alt="Логотип сайта Седона»">
обрати внимание на этот критерий https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-03

2022-06-04 12:03 UTC, Kartaviy-arteom commented on index.html
> +            <img class="advantages-housing" src="" width="75" height="72" alt="Картинка жильё">
декоративное изображение, сделаем на css

2022-06-04 12:03 UTC, Kartaviy-arteom commented on index.html
>              <img class="advantages-food" src="" alt="Картинка с бургером">
декоративное изображение, сделаем на css

2022-06-04 12:03 UTC, Kartaviy-arteom commented on index.html
>              <img class="advantages-souvenirs" src="" alt="Картинка сувениры">
декоративное изображение, сделаем на css

2022-06-04 12:03 UTC, Kartaviy-arteom commented on index.html
> +          <img class="page-header-logo" src="/images/HTML Academy.svg" width="115" height="33" alt="Логотип сайта Седона»">
наименование файлов

2022-06-05 11:58 UTC, Volkovak27 commented on catalog.html
> +        </ul>
Я сделала этот блок чуть иначе.. И присвоила классы ul и li. Обернула в span текст и класс оставила visually-hidden. В барбершоп там вообще просто спаном сделаны эти пункты. И я не очень понимаю как правильно.

2022-06-05 11:59 UTC, Volkovak27 commented on index.html
> +            <img class="advantages-housing" src="" width="75" height="72" alt="Картинка жильё">
да, я не убрала тут размер. Забыла. Изначально подумала, что эти иконки контентные, потом перечитала и поняла. но тут не убрала размеры.

2022-06-05 12:01 UTC, Volkovak27 commented on index.html
>              <img class="advantages-food" src="" alt="Картинка с бургером">
Получается тут вообще тогда не нужен img?

2022-06-05 12:01 UTC, Volkovak27 commented on index.html
>              <img class="advantages-souvenirs" src="" alt="Картинка сувениры">
И тут тоже?

2022-06-05 12:03 UTC, Volkovak27 commented on index.html
> +          <img class="page-header-logo" src="/images/HTML Academy.svg" width="115" height="33" alt="Логотип сайта Седона»">
исправила на название logo-footer.svg

2022-06-05 12:08 UTC, Volkovak27 commented on index.html
>              <img class="advantages-food" src="" alt="Картинка с бургером">
прописала вместо img <span class="visually-hidden">Картинка с бургером</span>
Только есть вопрос. Как тогда мы туда картинку сможем поместить. Нужно класс особый списку или что?

2022-06-05 12:09 UTC, Volkovak27 commented on index.html
>              <img class="advantages-souvenirs" src="" alt="Картинка сувениры">
Тоже самое тут вместо картинки <span class="visually-hidden">

2022-06-05 12:09 UTC, Volkovak27 commented on catalog.html
> +          <img class="page-header-logo" src="/images/HTML Academy.svg" width="115" height="33" alt="Логотип сайта Седона»">
исправила.

2022-06-05 18:56 UTC, Kartaviy-arteom approved these changes

2022-06-05 18:56 UTC, Kartaviy-arteom commented on index.html
> +            <span class="visually-hidden">Картинка жилье</span>
тебе нет смысла объяснять декоративное изображение, у тебя и так есть заголовок про жилье. Это не нужная информация. Нужно просто убрать этот span

2022-06-05 18:56 UTC, merged